import { defineConfig } from 'vite'
import { resolve } from 'path'

export default defineConfig({
  base: './',
  build: {
    rollupOptions: {
      input: {
        index: resolve(__dirname, 'index.html'),
        schools: resolve(__dirname, 'directory/schools.html'),
        hospitals: resolve(__dirname, 'directory/hospitals.html'),
        colleges: resolve(__dirname, 'directory/colleges.html'),
        temples: resolve(__dirname, 'directory/temples.html'),
        banks: resolve(__dirname, 'directory/banks.html'),
        libraries: resolve(__dirname, 'directory/libraries.html'),
        businesses: resolve(__dirname, 'directory/businesses.html'),
        jobs: resolve(__dirname, 'directory/jobs.html'),
        govt_jobs: resolve(__dirname, 'directory/government-jobs.html'),
        beauty_parlour: resolve(__dirname, 'directory/best-beauty-parlour-in-paraspur.html'),
        ladies_boutique: resolve(__dirname, 'directory/best-ladies-boutique-in-paraspur.html'),
        bridal_makeup: resolve(__dirname, 'directory/bridal-makeup-in-paraspur.html'),
        pbc_makeup_studio: resolve(__dirname, 'directory/pbc-makeup-studio-paraspur.html'),
        wedding_shopping: resolve(__dirname, 'directory/wedding-shopping-in-paraspur.html'),
        population: resolve(__dirname, 'info/population.html'),
        pincode: resolve(__dirname, 'info/pin-code.html'),
        history: resolve(__dirname, 'info/history.html'),
        news: resolve(__dirname, 'info/news.html'),
        politicians: resolve(__dirname, 'info/politicians.html'),
        durauni_chauraha: resolve(__dirname, 'info/durauni-chauraha.html'),
        clothing_shops: resolve(__dirname, 'directory/clothing-shops-paraspur.html'),
        restaurants: resolve(__dirname, 'directory/restaurants-paraspur.html'),
        photographers: resolve(__dirname, 'directory/wedding-photographers-paraspur.html'),
        transport: resolve(__dirname, 'directory/transport-services-paraspur.html'),
        agriculture: resolve(__dirname, 'directory/agriculture.html'),
        local_startups: resolve(__dirname, 'directory/local-startups.html'),
        jeevansaar_clinic: resolve(__dirname, 'directory/jeevansaar-homeopathy-clinic.html'),
        paraspur_market: resolve(__dirname, 'paraspur-market.html'),
        contact: resolve(__dirname, 'contact.html'),
        privacy: resolve(__dirname, 'privacy-policy.html'),
        terms: resolve(__dirname, 'terms.html'),
        disclaimer: resolve(__dirname, 'disclaimer.html'),
        about_website: resolve(__dirname, 'about-website.html'),
        itr_filing: resolve(__dirname, 'services/itr-filing-gonda-paraspur.html'),
        villages_list: resolve(__dirname, 'villages/index.html'),
        blog_tulsidas: resolve(__dirname, 'blog/tulsidas-ayodhya-paraspur-connection.html'),
        blog_villages: resolve(__dirname, 'blog/all-villages-in-paraspur-block.html'),
        blog_index: resolve(__dirname, 'blog/index.html'),
        beauty_blog: resolve(__dirname, 'blog/beauty-parlours-in-paraspur-gonda.html'),
        blog_scpm_nursing: resolve(__dirname, 'blog/scpm-college-of-nursing-bhulbhuliya.html'),
        v_paraspur: resolve(__dirname, 'villages/paraspur.html'),
        v_pasaka: resolve(__dirname, 'villages/pasaka.html'),
        v_durauni: resolve(__dirname, 'villages/durauni.html'),
        v_sakraur: resolve(__dirname, 'villages/sakraur.html'),
        v_bhauri_ganj: resolve(__dirname, 'villages/bhauri-ganj.html'),
        v_mangura_bazar: resolve(__dirname, 'villages/mangura-bazar.html'),
        gonda_history: resolve(__dirname, 'gonda/history.html'),
        gonda_index: resolve(__dirname, 'gonda/index.html'),
        agri_index: resolve(__dirname, 'agriculture/index.html'),
        agri_mandi: resolve(__dirname, 'agriculture/mandi-bhav.html'),
        agri_gonda: resolve(__dirname, 'agriculture/seeds-gonda.html'),
      }
    }
  }
})
